# see https://community.chocolatey.org/packages/visualstudio2026community
# NB visual studio community does not really allow the installation of a
#    specific version, so this chocolatey package version is used as a
#    workaround for forcing the user to upgrade to the latest version.
# renovate: datasource=nuget:chocolatey depName=visualstudio2026community
visual_studio_vs_version: '118.2.0' # Visual Studio 18.2.0.
