# see https://community.chocolatey.org/packages/dotnet-sdk
# see https://dotnet.microsoft.com/en-us/download/dotnet/8.0
# see https://learn.microsoft.com/en-us/dotnet/core/install/windows
# renovate: datasource=nuget:chocolatey depName=dotnet-sdk extractVersion=(?<version>8\.0\..+)
dotnet_sdk_8_version: '8.0.417' # dotnet 8.0.23

# see https://community.chocolatey.org/packages/dotnet-sdk
# see https://dotnet.microsoft.com/en-us/download/dotnet/10.0
# see https://learn.microsoft.com/en-us/dotnet/core/install/windows
# renovate: datasource=nuget:chocolatey depName=dotnet-sdk extractVersion=(?<version>10\.0\..+)
dotnet_sdk_10_version: '10.0.101' # dotnet 10.0.1

dotnet_sdk_versions:
  - '{{ dotnet_sdk_8_version }}'
  - '{{ dotnet_sdk_10_version }}'
